language: scala
scala:
  - 2.12.4
jdk:
  - oraclejdk8
before_install:
  - export PATH=${PATH}:./vendor/bundle
install:
  - rvm use 2.3.3 --install --fuzzy
  - gem update --system
  - gem install sass
  - gem install jekyll -v 3.6.2
script:
  - echo java -version
  - sbt ++$TRAVIS_SCALA_VERSION test:compile test
  - sbt ++$TRAVIS_SCALA_VERSION publishLocal
