name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: olafurpg/setup-scala@v7
        with:
          java-version: adopt@1.11.0-9
      - name: Checking your code format
        run: |
          java -version
          sbt scalafmtCheckAll
      - name: Run tests
        run: csbt +test
